server:
  port: 8584

spring:
  application:
    name: wigell-padel

  datasource:
    url: jdbc:mysql://localhost:3306/wigell_padel_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/wigell-realm

  boot:
    admin:
      client:
        url: http://localhost:8081

wigell:
  currency:
    url: http://localhost:8080/currency

management:
  endpoints:
    web:
      exposure:
        include: health, info
  info:
    env:
      enabled: true

keycloak:
  admin:
    server-url: http://localhost:8180
    realm: wigell-realm
    client-id: wigell-padel-client
    client-secret: din-hemliga-kod-här # Hämta denna från 'Credentials' fliken i Keycloak

logging:
  level:
    root: INFO
    com.nilsson.padel: DEBUG
    com.groupc.shared: DEBUG